### ISSUE TITLE
I fixed the dvorak version of this keyboard for the most part on the cyanogenmod branch

### ISSUE THREAD

**Issue by that1communist** [PureNexusProject/android_packages_inputmethods_LatinIME#1]
This is the rom I actually use so I was wondering if it could be included here.

Also, is there any way to make it so that the popup for the options on the period is instant, so that you can get that immediate slide to questionmark/whatnot that most keyboards have? I mean... i'm sure there is, but I don't even know where to begin on that, and I'd prefer that fix would be pushed up to Cyanogenmod, but they're a much bigger project and I feel I have no chance for a response there.

These two things would make it the perfect keyboard for me, finally a completely FOSS android keyboard thats actually great... I just wish it could be on the playstore.

https://github.com/CyanogenMod/android_packages_inputmethods_LatinIME/pull/10

https://github.com/CyanogenMod/android_packages_inputmethods_LatinIME/pull/9

https://github.com/CyanogenMod/android_packages_inputmethods_LatinIME/pull/8

**Comment by beanstown106** [comment]
thanks again for this, can u confirm this commit is the same as the above three ^^ https://github.com/PureNexusProject/android_packages_inputmethods_LatinIME/commit/83d50c5f2a3eed8f3173025eebdf85d78d08635c

**Comment by that1communist** [comment]
Looks good to me! Thank you!
